package timeout

// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/timeout.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"
	"fmt"
	"time"

	"go.uber.org/yarpc"

	"github.com/uber/cadence/client/sharddistributor"
	"github.com/uber/cadence/common/types"
)

var _ sharddistributor.Client = (*sharddistributorClient)(nil)

// sharddistributorClient implements the sharddistributor.Client interface instrumented with timeouts
type sharddistributorClient struct {
	client  sharddistributor.Client
	timeout time.Duration
}

// NewShardDistributorClient creates a new sharddistributorClient instance
func NewShardDistributorClient(
	client sharddistributor.Client,
	timeout time.Duration,
) sharddistributor.Client {
	return &sharddistributorClient{
		client:  client,
		timeout: timeout,
	}
}

func (c *sharddistributorClient) GetShardOwner(ctx context.Context, gp1 *types.GetShardOwnerRequest, p1 ...yarpc.CallOption) (gp2 *types.GetShardOwnerResponse, err error) {
	ctx, cancel := createContext(ctx, c.timeout)
	fmt.Println("GetShardOwner timeout", c.timeout)
	defer cancel()

	gp2, err = c.client.GetShardOwner(ctx, gp1, p1...)
	if err != nil {
		fmt.Println("GetShardOwner error", err)
		return nil, err
	}

	fmt.Println("GetShardOwner result", gp2)

	return
}

func (c *sharddistributorClient) WatchNamespaceState(ctx context.Context, wp1 *types.WatchNamespaceStateRequest, p1 ...yarpc.CallOption) (w1 sharddistributor.WatchNamespaceStateClient, err error) {
	return c.client.WatchNamespaceState(ctx, wp1, p1...)
}
