// The MIT License (MIT)

// Copyright (c) 2017-2020 Uber Technologies Inc.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uber/cadence/shardmanager/v1/control.proto

package shardmanagerv1

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ShardLoadInfo struct {
	ShardKey             string   `protobuf:"bytes,1,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	Load                 float64  `protobuf:"fixed64,2,opt,name=load,proto3" json:"load,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardLoadInfo) Reset()         { *m = ShardLoadInfo{} }
func (m *ShardLoadInfo) String() string { return proto.CompactTextString(m) }
func (*ShardLoadInfo) ProtoMessage()    {}
func (*ShardLoadInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b31fbf2f1f3b1d, []int{0}
}
func (m *ShardLoadInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShardLoadInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ShardLoadInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ShardLoadInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardLoadInfo.Merge(m, src)
}
func (m *ShardLoadInfo) XXX_Size() int {
	return m.Size()
}
func (m *ShardLoadInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardLoadInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShardLoadInfo proto.InternalMessageInfo

func (m *ShardLoadInfo) GetShardKey() string {
	if m != nil {
		return m.ShardKey
	}
	return ""
}

func (m *ShardLoadInfo) GetLoad() float64 {
	if m != nil {
		return m.Load
	}
	return 0
}

type HearthBeatRequest struct {
	HostInfo             string           `protobuf:"bytes,1,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`
	ShardLoads           []*ShardLoadInfo `protobuf:"bytes,2,rep,name=shard_loads,json=shardLoads,proto3" json:"shard_loads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HearthBeatRequest) Reset()         { *m = HearthBeatRequest{} }
func (m *HearthBeatRequest) String() string { return proto.CompactTextString(m) }
func (*HearthBeatRequest) ProtoMessage()    {}
func (*HearthBeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b31fbf2f1f3b1d, []int{1}
}
func (m *HearthBeatRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HearthBeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HearthBeatRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HearthBeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HearthBeatRequest.Merge(m, src)
}
func (m *HearthBeatRequest) XXX_Size() int {
	return m.Size()
}
func (m *HearthBeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HearthBeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HearthBeatRequest proto.InternalMessageInfo

func (m *HearthBeatRequest) GetHostInfo() string {
	if m != nil {
		return m.HostInfo
	}
	return ""
}

func (m *HearthBeatRequest) GetShardLoads() []*ShardLoadInfo {
	if m != nil {
		return m.ShardLoads
	}
	return nil
}

type HearthBeatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HearthBeatResponse) Reset()         { *m = HearthBeatResponse{} }
func (m *HearthBeatResponse) String() string { return proto.CompactTextString(m) }
func (*HearthBeatResponse) ProtoMessage()    {}
func (*HearthBeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b31fbf2f1f3b1d, []int{2}
}
func (m *HearthBeatResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HearthBeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HearthBeatResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HearthBeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HearthBeatResponse.Merge(m, src)
}
func (m *HearthBeatResponse) XXX_Size() int {
	return m.Size()
}
func (m *HearthBeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HearthBeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HearthBeatResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ShardLoadInfo)(nil), "uber.cadence.shardmanager.v1.ShardLoadInfo")
	proto.RegisterType((*HearthBeatRequest)(nil), "uber.cadence.shardmanager.v1.HearthBeatRequest")
	proto.RegisterType((*HearthBeatResponse)(nil), "uber.cadence.shardmanager.v1.HearthBeatResponse")
}

func init() {
	proto.RegisterFile("uber/cadence/shardmanager/v1/control.proto", fileDescriptor_84b31fbf2f1f3b1d)
}

var fileDescriptor_84b31fbf2f1f3b1d = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4f, 0x4b, 0xf3, 0x30,
	0x1c, 0x26, 0x7b, 0x5f, 0xc4, 0x65, 0x78, 0x30, 0x88, 0x0c, 0x95, 0x52, 0x7a, 0x2a, 0x0a, 0xc9,
	0x3a, 0x8f, 0x5e, 0xdc, 0xbc, 0x38, 0x9c, 0x28, 0xf5, 0xe6, 0x65, 0xa4, 0xed, 0x6f, 0xed, 0x70,
	0x4b, 0x66, 0x92, 0x16, 0x76, 0xf1, 0x1b, 0xf8, 0xbd, 0x3c, 0xfa, 0x11, 0xa4, 0x9f, 0x44, 0x9a,
	0x3a, 0xec, 0x14, 0x86, 0xb7, 0xfe, 0x1e, 0x9e, 0x7f, 0xcd, 0x83, 0x4f, 0xf3, 0x08, 0x14, 0x8b,
	0x79, 0x02, 0x22, 0x06, 0xa6, 0x33, 0xae, 0x92, 0x05, 0x17, 0x3c, 0x05, 0xc5, 0x8a, 0x80, 0xc5,
	0x52, 0x18, 0x25, 0xe7, 0x74, 0xa9, 0xa4, 0x91, 0xe4, 0xa4, 0xe2, 0xd2, 0x2f, 0x2e, 0x6d, 0x72,
	0x69, 0x11, 0x78, 0x97, 0x78, 0xef, 0xa1, 0x82, 0xc6, 0x92, 0x27, 0x23, 0x31, 0x95, 0xe4, 0x18,
	0xb7, 0x2d, 0x67, 0xf2, 0x04, 0xab, 0x2e, 0x72, 0x91, 0xdf, 0x0e, 0x77, 0x2d, 0x70, 0x03, 0x2b,
	0x42, 0xf0, 0xff, 0xb9, 0xe4, 0x49, 0xb7, 0xe5, 0x22, 0x1f, 0x85, 0xf6, 0xdb, 0x7b, 0xc1, 0xfb,
	0xd7, 0xc0, 0x95, 0xc9, 0x86, 0xc0, 0x4d, 0x08, 0xcf, 0x39, 0x68, 0x53, 0xb9, 0x64, 0x52, 0x9b,
	0xc9, 0x4c, 0x4c, 0xe5, 0xda, 0xa5, 0x02, 0x6c, 0xc4, 0x18, 0x77, 0xea, 0x88, 0x4a, 0xaf, 0xbb,
	0x2d, 0xf7, 0x9f, 0xdf, 0xe9, 0x9f, 0xd1, 0x6d, 0x3d, 0xe9, 0x46, 0xc9, 0x10, 0xeb, 0xf5, 0xa9,
	0xbd, 0x03, 0x4c, 0x9a, 0xf9, 0x7a, 0x29, 0x85, 0x86, 0xfe, 0x2b, 0xc2, 0x87, 0x56, 0x73, 0x5b,
	0x7b, 0x5c, 0xd5, 0x6f, 0x32, 0xb8, 0x1f, 0x11, 0x8d, 0xf1, 0xb7, 0x80, 0xb0, 0xed, 0xb9, 0xbf,
	0x7e, 0xed, 0xa8, 0xf7, 0x77, 0x41, 0xdd, 0xc5, 0x47, 0x3d, 0x34, 0xbc, 0x7b, 0x2b, 0x1d, 0xf4,
	0x5e, 0x3a, 0xe8, 0xa3, 0x74, 0xd0, 0xe3, 0x20, 0x9d, 0x99, 0x2c, 0x8f, 0x68, 0x2c, 0x17, 0x6c,
	0x63, 0x4a, 0x9a, 0x82, 0x60, 0x76, 0xb7, 0x9f, 0xab, 0x5e, 0x34, 0xef, 0x22, 0x88, 0x76, 0x2c,
	0xeb, 0xfc, 0x33, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x84, 0x64, 0x7a, 0x0b, 0x02, 0x00, 0x00,
}

func (m *ShardLoadInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShardLoadInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ShardLoadInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Load != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Load))))
		i--
		dAtA[i] = 0x11
	}
	if len(m.ShardKey) > 0 {
		i -= len(m.ShardKey)
		copy(dAtA[i:], m.ShardKey)
		i = encodeVarintControl(dAtA, i, uint64(len(m.ShardKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HearthBeatRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HearthBeatRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HearthBeatRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ShardLoads) > 0 {
		for iNdEx := len(m.ShardLoads) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ShardLoads[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintControl(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.HostInfo) > 0 {
		i -= len(m.HostInfo)
		copy(dAtA[i:], m.HostInfo)
		i = encodeVarintControl(dAtA, i, uint64(len(m.HostInfo)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HearthBeatResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HearthBeatResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HearthBeatResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func encodeVarintControl(dAtA []byte, offset int, v uint64) int {
	offset -= sovControl(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ShardLoadInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ShardKey)
	if l > 0 {
		n += 1 + l + sovControl(uint64(l))
	}
	if m.Load != 0 {
		n += 9
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *HearthBeatRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.HostInfo)
	if l > 0 {
		n += 1 + l + sovControl(uint64(l))
	}
	if len(m.ShardLoads) > 0 {
		for _, e := range m.ShardLoads {
			l = e.Size()
			n += 1 + l + sovControl(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *HearthBeatResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovControl(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozControl(x uint64) (n int) {
	return sovControl(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ShardLoadInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowControl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShardLoadInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShardLoadInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthControl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthControl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShardKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Load", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Load = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipControl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthControl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HearthBeatRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowControl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HearthBeatRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HearthBeatRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthControl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthControl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostInfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardLoads", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthControl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthControl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShardLoads = append(m.ShardLoads, &ShardLoadInfo{})
			if err := m.ShardLoads[len(m.ShardLoads)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipControl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthControl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HearthBeatResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowControl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HearthBeatResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HearthBeatResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipControl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthControl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipControl(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowControl
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowControl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowControl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthControl
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupControl
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthControl
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthControl        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowControl          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupControl = fmt.Errorf("proto: unexpected end of group")
)
