// The MIT License (MIT)

// Copyright (c) 2017-2020 Uber Technologies Inc.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/shardmanager/v1/service.proto

package shardmanagerv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// ShardManagerAPIYARPCClient is the YARPC client-side interface for the ShardManagerAPI service.
type ShardManagerAPIYARPCClient interface {
	GetShardOwner(context.Context, ...yarpc.CallOption) (ShardManagerAPIServiceGetShardOwnerYARPCClient, error)
}

// ShardManagerAPIServiceGetShardOwnerYARPCClient sends GetShardOwnerRequests and receives GetShardOwnerResponses, returning io.EOF when the stream is complete.
type ShardManagerAPIServiceGetShardOwnerYARPCClient interface {
	Context() context.Context
	Send(*GetShardOwnerRequest, ...yarpc.StreamOption) error
	Recv(...yarpc.StreamOption) (*GetShardOwnerResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

func newShardManagerAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) ShardManagerAPIYARPCClient {
	return &_ShardManagerAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.shardmanager.v1.ShardManagerAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewShardManagerAPIYARPCClient builds a new YARPC client for the ShardManagerAPI service.
func NewShardManagerAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) ShardManagerAPIYARPCClient {
	return newShardManagerAPIYARPCClient(clientConfig, nil, options...)
}

// ShardManagerAPIYARPCServer is the YARPC server-side interface for the ShardManagerAPI service.
type ShardManagerAPIYARPCServer interface {
	GetShardOwner(ShardManagerAPIServiceGetShardOwnerYARPCServer) error
}

// ShardManagerAPIServiceGetShardOwnerYARPCServer receives GetShardOwnerRequests and sends GetShardOwnerResponse.
type ShardManagerAPIServiceGetShardOwnerYARPCServer interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetShardOwnerRequest, error)
	Send(*GetShardOwnerResponse, ...yarpc.StreamOption) error
}

type buildShardManagerAPIYARPCProceduresParams struct {
	Server      ShardManagerAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildShardManagerAPIYARPCProcedures(params buildShardManagerAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_ShardManagerAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName:         "uber.cadence.shardmanager.v1.ShardManagerAPI",
			UnaryHandlerParams:  []protobuf.BuildProceduresUnaryHandlerParams{},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{
				{
					MethodName: "GetShardOwner",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.GetShardOwner,
						},
					),
				},
			},
		},
	)
}

// BuildShardManagerAPIYARPCProcedures prepares an implementation of the ShardManagerAPI service for YARPC registration.
func BuildShardManagerAPIYARPCProcedures(server ShardManagerAPIYARPCServer) []transport.Procedure {
	return buildShardManagerAPIYARPCProcedures(buildShardManagerAPIYARPCProceduresParams{Server: server})
}

// FxShardManagerAPIYARPCClientParams defines the input
// for NewFxShardManagerAPIYARPCClient. It provides the
// paramaters to get a ShardManagerAPIYARPCClient in an
// Fx application.
type FxShardManagerAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxShardManagerAPIYARPCClientResult defines the output
// of NewFxShardManagerAPIYARPCClient. It provides a
// ShardManagerAPIYARPCClient to an Fx application.
type FxShardManagerAPIYARPCClientResult struct {
	fx.Out

	Client ShardManagerAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxShardManagerAPIYARPCClient provides a ShardManagerAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  shardmanagerv1.NewFxShardManagerAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxShardManagerAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxShardManagerAPIYARPCClientParams) FxShardManagerAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxShardManagerAPIYARPCClientResult{
			Client: newShardManagerAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxShardManagerAPIYARPCProceduresParams defines the input
// for NewFxShardManagerAPIYARPCProcedures. It provides the
// paramaters to get ShardManagerAPIYARPCServer procedures in an
// Fx application.
type FxShardManagerAPIYARPCProceduresParams struct {
	fx.In

	Server      ShardManagerAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxShardManagerAPIYARPCProceduresResult defines the output
// of NewFxShardManagerAPIYARPCProcedures. It provides
// ShardManagerAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxShardManagerAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxShardManagerAPIYARPCProcedures provides ShardManagerAPIYARPCServer procedures to an Fx application.
// It expects a ShardManagerAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  shardmanagerv1.NewFxShardManagerAPIYARPCProcedures(),
//	  ...
//	)
func NewFxShardManagerAPIYARPCProcedures() interface{} {
	return func(params FxShardManagerAPIYARPCProceduresParams) FxShardManagerAPIYARPCProceduresResult {
		return FxShardManagerAPIYARPCProceduresResult{
			Procedures: buildShardManagerAPIYARPCProcedures(buildShardManagerAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: ShardManagerAPIReflectionMeta,
		}
	}
}

// ShardManagerAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var ShardManagerAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.shardmanager.v1.ShardManagerAPI",
	FileDescriptors: yarpcFileDescriptorClosure889886f494a83aa4,
}

type _ShardManagerAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_ShardManagerAPIYARPCCaller) GetShardOwner(ctx context.Context, options ...yarpc.CallOption) (ShardManagerAPIServiceGetShardOwnerYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "GetShardOwner", options...)
	if err != nil {
		return nil, err
	}
	return &_ShardManagerAPIServiceGetShardOwnerYARPCClient{stream: stream}, nil
}

type _ShardManagerAPIYARPCHandler struct {
	server ShardManagerAPIYARPCServer
}

func (h *_ShardManagerAPIYARPCHandler) GetShardOwner(serverStream *protobuf.ServerStream) error {
	return h.server.GetShardOwner(&_ShardManagerAPIServiceGetShardOwnerYARPCServer{serverStream: serverStream})
}

type _ShardManagerAPIServiceGetShardOwnerYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_ShardManagerAPIServiceGetShardOwnerYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_ShardManagerAPIServiceGetShardOwnerYARPCClient) Send(request *GetShardOwnerRequest, options ...yarpc.StreamOption) error {
	return c.stream.Send(request, options...)
}

func (c *_ShardManagerAPIServiceGetShardOwnerYARPCClient) Recv(options ...yarpc.StreamOption) (*GetShardOwnerResponse, error) {
	responseMessage, err := c.stream.Receive(newShardManagerAPIServiceGetShardOwnerYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetShardOwnerResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardManagerAPIServiceGetShardOwnerYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardManagerAPIServiceGetShardOwnerYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _ShardManagerAPIServiceGetShardOwnerYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_ShardManagerAPIServiceGetShardOwnerYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_ShardManagerAPIServiceGetShardOwnerYARPCServer) Recv(options ...yarpc.StreamOption) (*GetShardOwnerRequest, error) {
	requestMessage, err := s.serverStream.Receive(newShardManagerAPIServiceGetShardOwnerYARPCRequest, options...)
	if requestMessage == nil {
		return nil, err
	}
	request, ok := requestMessage.(*GetShardOwnerRequest)
	if !ok {
		return nil, protobuf.CastError(emptyShardManagerAPIServiceGetShardOwnerYARPCRequest, requestMessage)
	}
	return request, err
}

func (s *_ShardManagerAPIServiceGetShardOwnerYARPCServer) Send(response *GetShardOwnerResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

func newShardManagerAPIServiceGetShardOwnerYARPCRequest() proto.Message {
	return &GetShardOwnerRequest{}
}

func newShardManagerAPIServiceGetShardOwnerYARPCResponse() proto.Message {
	return &GetShardOwnerResponse{}
}

var (
	emptyShardManagerAPIServiceGetShardOwnerYARPCRequest  = &GetShardOwnerRequest{}
	emptyShardManagerAPIServiceGetShardOwnerYARPCResponse = &GetShardOwnerResponse{}
)

var yarpcFileDescriptorClosure889886f494a83aa4 = [][]byte{
	// uber/cadence/shardmanager/v1/service.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2a, 0x4d, 0x4a, 0x2d,
		0xd2, 0x4f, 0x4e, 0x4c, 0x49, 0xcd, 0x4b, 0x4e, 0xd5, 0x2f, 0xce, 0x48, 0x2c, 0x4a, 0xc9, 0x4d,
		0xcc, 0x4b, 0x4c, 0x4f, 0x2d, 0xd2, 0x2f, 0x33, 0xd4, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
		0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x01, 0xa9, 0xd5, 0x83, 0xaa, 0xd5, 0x43, 0x56,
		0xab, 0x57, 0x66, 0xa8, 0x64, 0xcc, 0x25, 0xe2, 0x9e, 0x5a, 0x12, 0x0c, 0x12, 0xf5, 0x2f, 0xcf,
		0x4b, 0x2d, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe6, 0xe2, 0x04, 0x2b, 0x8d,
		0xcf, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x00, 0x0b, 0x78, 0xa7, 0x56,
		0x2a, 0x79, 0x71, 0x89, 0xa2, 0x69, 0x2a, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xc5, 0xab, 0x4b, 0x48,
		0x84, 0x8b, 0x35, 0x1f, 0xa4, 0x5a, 0x82, 0x09, 0x2c, 0x01, 0xe1, 0x18, 0xf5, 0x33, 0x72, 0xf1,
		0x83, 0x4d, 0xf2, 0x85, 0x38, 0xca, 0x31, 0xc0, 0x53, 0xa8, 0x86, 0x8b, 0x17, 0xc5, 0x7c, 0x21,
		0x23, 0x3d, 0x7c, 0x9e, 0xd0, 0xc3, 0xe6, 0x03, 0x29, 0x63, 0x92, 0xf4, 0x40, 0x3c, 0xa0, 0xc1,
		0x68, 0xc0, 0xe8, 0xe4, 0x1c, 0xe5, 0x98, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f,
		0xab, 0x8f, 0x12, 0xd2, 0x7a, 0xe9, 0xa9, 0x79, 0xfa, 0xe0, 0x60, 0x45, 0x0f, 0x74, 0x6b, 0x64,
		0x7e, 0x99, 0x61, 0x12, 0x1b, 0x58, 0x95, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x94, 0x13, 0x93,
		0x5c, 0xaa, 0x01, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) ShardManagerAPIYARPCClient {
			return NewShardManagerAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
