// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/sharddistributor/v1/service.proto

package sharddistributorv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// ShardDistributorAPIYARPCClient is the YARPC client-side interface for the ShardDistributorAPI service.
type ShardDistributorAPIYARPCClient interface {
	GetShardOwner(context.Context, *GetShardOwnerRequest, ...yarpc.CallOption) (*GetShardOwnerResponse, error)
	NewEphemeralShard(context.Context, *NewEphemeralShardRequest, ...yarpc.CallOption) (*NewEphemeralShardResponse, error)
}

func newShardDistributorAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) ShardDistributorAPIYARPCClient {
	return &_ShardDistributorAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewShardDistributorAPIYARPCClient builds a new YARPC client for the ShardDistributorAPI service.
func NewShardDistributorAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) ShardDistributorAPIYARPCClient {
	return newShardDistributorAPIYARPCClient(clientConfig, nil, options...)
}

// ShardDistributorAPIYARPCServer is the YARPC server-side interface for the ShardDistributorAPI service.
type ShardDistributorAPIYARPCServer interface {
	GetShardOwner(context.Context, *GetShardOwnerRequest) (*GetShardOwnerResponse, error)
	NewEphemeralShard(context.Context, *NewEphemeralShardRequest) (*NewEphemeralShardResponse, error)
}

type buildShardDistributorAPIYARPCProceduresParams struct {
	Server      ShardDistributorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildShardDistributorAPIYARPCProcedures(params buildShardDistributorAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_ShardDistributorAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "GetShardOwner",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.GetShardOwner,
							NewRequest:  newShardDistributorAPIServiceGetShardOwnerYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "NewEphemeralShard",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.NewEphemeralShard,
							NewRequest:  newShardDistributorAPIServiceNewEphemeralShardYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildShardDistributorAPIYARPCProcedures prepares an implementation of the ShardDistributorAPI service for YARPC registration.
func BuildShardDistributorAPIYARPCProcedures(server ShardDistributorAPIYARPCServer) []transport.Procedure {
	return buildShardDistributorAPIYARPCProcedures(buildShardDistributorAPIYARPCProceduresParams{Server: server})
}

// FxShardDistributorAPIYARPCClientParams defines the input
// for NewFxShardDistributorAPIYARPCClient. It provides the
// paramaters to get a ShardDistributorAPIYARPCClient in an
// Fx application.
type FxShardDistributorAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxShardDistributorAPIYARPCClientResult defines the output
// of NewFxShardDistributorAPIYARPCClient. It provides a
// ShardDistributorAPIYARPCClient to an Fx application.
type FxShardDistributorAPIYARPCClientResult struct {
	fx.Out

	Client ShardDistributorAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxShardDistributorAPIYARPCClient provides a ShardDistributorAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxShardDistributorAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxShardDistributorAPIYARPCClientParams) FxShardDistributorAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxShardDistributorAPIYARPCClientResult{
			Client: newShardDistributorAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxShardDistributorAPIYARPCProceduresParams defines the input
// for NewFxShardDistributorAPIYARPCProcedures. It provides the
// paramaters to get ShardDistributorAPIYARPCServer procedures in an
// Fx application.
type FxShardDistributorAPIYARPCProceduresParams struct {
	fx.In

	Server      ShardDistributorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxShardDistributorAPIYARPCProceduresResult defines the output
// of NewFxShardDistributorAPIYARPCProcedures. It provides
// ShardDistributorAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxShardDistributorAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxShardDistributorAPIYARPCProcedures provides ShardDistributorAPIYARPCServer procedures to an Fx application.
// It expects a ShardDistributorAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorAPIYARPCProcedures(),
//	  ...
//	)
func NewFxShardDistributorAPIYARPCProcedures() interface{} {
	return func(params FxShardDistributorAPIYARPCProceduresParams) FxShardDistributorAPIYARPCProceduresResult {
		return FxShardDistributorAPIYARPCProceduresResult{
			Procedures: buildShardDistributorAPIYARPCProcedures(buildShardDistributorAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: ShardDistributorAPIReflectionMeta,
		}
	}
}

// ShardDistributorAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var ShardDistributorAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
	FileDescriptors: yarpcFileDescriptorClosure0055bfd59dff1f95,
}

type _ShardDistributorAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_ShardDistributorAPIYARPCCaller) GetShardOwner(ctx context.Context, request *GetShardOwnerRequest, options ...yarpc.CallOption) (*GetShardOwnerResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetShardOwner", request, newShardDistributorAPIServiceGetShardOwnerYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetShardOwnerResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetShardOwnerYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) NewEphemeralShard(ctx context.Context, request *NewEphemeralShardRequest, options ...yarpc.CallOption) (*NewEphemeralShardResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "NewEphemeralShard", request, newShardDistributorAPIServiceNewEphemeralShardYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*NewEphemeralShardResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceNewEphemeralShardYARPCResponse, responseMessage)
	}
	return response, err
}

type _ShardDistributorAPIYARPCHandler struct {
	server ShardDistributorAPIYARPCServer
}

func (h *_ShardDistributorAPIYARPCHandler) GetShardOwner(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetShardOwnerRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetShardOwnerRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetShardOwnerYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetShardOwner(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) NewEphemeralShard(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *NewEphemeralShardRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*NewEphemeralShardRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceNewEphemeralShardYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.NewEphemeralShard(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newShardDistributorAPIServiceGetShardOwnerYARPCRequest() proto.Message {
	return &GetShardOwnerRequest{}
}

func newShardDistributorAPIServiceGetShardOwnerYARPCResponse() proto.Message {
	return &GetShardOwnerResponse{}
}

func newShardDistributorAPIServiceNewEphemeralShardYARPCRequest() proto.Message {
	return &NewEphemeralShardRequest{}
}

func newShardDistributorAPIServiceNewEphemeralShardYARPCResponse() proto.Message {
	return &NewEphemeralShardResponse{}
}

var (
	emptyShardDistributorAPIServiceGetShardOwnerYARPCRequest      = &GetShardOwnerRequest{}
	emptyShardDistributorAPIServiceGetShardOwnerYARPCResponse     = &GetShardOwnerResponse{}
	emptyShardDistributorAPIServiceNewEphemeralShardYARPCRequest  = &NewEphemeralShardRequest{}
	emptyShardDistributorAPIServiceNewEphemeralShardYARPCResponse = &NewEphemeralShardResponse{}
)

var yarpcFileDescriptorClosure0055bfd59dff1f95 = [][]byte{
	// uber/cadence/sharddistributor/v1/service.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
		0x14, 0x24, 0x05, 0xc5, 0x3e, 0xf0, 0xe0, 0x5a, 0xa5, 0x56, 0x0f, 0xa5, 0x27, 0x4f, 0xbb, 0x54,
		0xa1, 0x82, 0x3d, 0x29, 0x56, 0x29, 0x85, 0x56, 0x2b, 0x5e, 0xbc, 0x48, 0x3e, 0x1e, 0x4d, 0xd0,
		0xec, 0xc6, 0xdd, 0x4d, 0x4a, 0x6f, 0xfe, 0x00, 0xff, 0x87, 0x7f, 0x53, 0xb2, 0x8d, 0x94, 0xc4,
		0x48, 0x68, 0xf1, 0xb8, 0xb3, 0x33, 0xc3, 0x9b, 0xf7, 0x01, 0x34, 0x76, 0x50, 0x32, 0xd7, 0xf6,
		0x90, 0xbb, 0xc8, 0x94, 0x6f, 0x4b, 0xcf, 0x0b, 0x94, 0x96, 0x81, 0x13, 0x6b, 0x21, 0x59, 0xd2,
		0x65, 0x0a, 0x65, 0x12, 0xb8, 0x48, 0x23, 0x29, 0xb4, 0x20, 0xed, 0x94, 0x4f, 0x33, 0x3e, 0x2d,
		0xf2, 0x69, 0xd2, 0xed, 0x3c, 0x40, 0xe3, 0x0e, 0xf5, 0x63, 0xfa, 0x33, 0x99, 0x73, 0x94, 0x53,
		0x7c, 0x8f, 0x51, 0x69, 0x72, 0x0c, 0x75, 0x43, 0x7f, 0x79, 0xc5, 0x45, 0xd3, 0x6a, 0x5b, 0xa7,
		0xf5, 0xe9, 0x8e, 0x01, 0x46, 0xb8, 0x20, 0x27, 0x50, 0xe7, 0x76, 0x88, 0x2a, 0xb2, 0x5d, 0x6c,
		0xd6, 0xcc, 0xe7, 0x0a, 0xe8, 0x8c, 0xe0, 0xa0, 0x60, 0xa9, 0x22, 0xc1, 0x15, 0x92, 0x06, 0x6c,
		0x89, 0x14, 0xc8, 0xfc, 0x96, 0x8f, 0x0a, 0xb3, 0x1e, 0x1c, 0x8e, 0x7f, 0x1e, 0x63, 0xa1, 0x6f,
		0x45, 0xcc, 0xbd, 0x81, 0x94, 0xa2, 0xa0, 0xb3, 0x8a, 0xba, 0x09, 0x10, 0x53, 0xc1, 0x1a, 0x9a,
		0x7c, 0xe6, 0x5a, 0x3e, 0x73, 0xe7, 0x09, 0x9a, 0x63, 0x9c, 0x0f, 0x22, 0x1f, 0x43, 0x94, 0xf6,
		0x9b, 0x31, 0xff, 0x87, 0x66, 0x4d, 0xe0, 0xa8, 0xc4, 0x76, 0xf3, 0x86, 0x9d, 0x7d, 0xd5, 0x60,
		0xdf, 0xb8, 0xdc, 0xac, 0x06, 0x7d, 0x75, 0x3f, 0x24, 0x1f, 0x16, 0xec, 0xe6, 0xc6, 0x42, 0x7a,
		0xb4, 0x6a, 0x3b, 0x68, 0xd9, 0x6a, 0xb4, 0x2e, 0xd6, 0xd6, 0x65, 0x71, 0x3e, 0x2d, 0xd8, 0xfb,
		0x15, 0x96, 0x5c, 0x56, 0xdb, 0xfd, 0xd5, 0xf8, 0x56, 0x7f, 0x23, 0xed, 0xb2, 0x9c, 0xeb, 0xd1,
		0xf3, 0x70, 0x16, 0x68, 0x3f, 0x76, 0xa8, 0x2b, 0x42, 0x96, 0xbb, 0x2c, 0x3a, 0x43, 0xce, 0xcc,
		0x09, 0x95, 0x1d, 0x59, 0xbf, 0x88, 0x25, 0x5d, 0x67, 0xdb, 0xb0, 0xcf, 0xbf, 0x03, 0x00, 0x00,
		0xff, 0xff, 0x6c, 0x25, 0x0f, 0xb4, 0xa2, 0x03, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) ShardDistributorAPIYARPCClient {
			return NewShardDistributorAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
