// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/sharddistributor/v1/service.proto

package sharddistributorv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// ShardDistributorAPIYARPCClient is the YARPC client-side interface for the ShardDistributorAPI service.
type ShardDistributorAPIYARPCClient interface {
	GetShardOwner(context.Context, *GetShardOwnerRequest, ...yarpc.CallOption) (*GetShardOwnerResponse, error)
	WatchNamespaceState(context.Context, *WatchNamespaceStateRequest, ...yarpc.CallOption) (ShardDistributorAPIServiceWatchNamespaceStateYARPCClient, error)
}

// ShardDistributorAPIServiceWatchNamespaceStateYARPCClient receives WatchNamespaceStateResponses, returning io.EOF when the stream is complete.
type ShardDistributorAPIServiceWatchNamespaceStateYARPCClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*WatchNamespaceStateResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

func newShardDistributorAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) ShardDistributorAPIYARPCClient {
	return &_ShardDistributorAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewShardDistributorAPIYARPCClient builds a new YARPC client for the ShardDistributorAPI service.
func NewShardDistributorAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) ShardDistributorAPIYARPCClient {
	return newShardDistributorAPIYARPCClient(clientConfig, nil, options...)
}

// ShardDistributorAPIYARPCServer is the YARPC server-side interface for the ShardDistributorAPI service.
type ShardDistributorAPIYARPCServer interface {
	GetShardOwner(context.Context, *GetShardOwnerRequest) (*GetShardOwnerResponse, error)
	WatchNamespaceState(*WatchNamespaceStateRequest, ShardDistributorAPIServiceWatchNamespaceStateYARPCServer) error
}

// ShardDistributorAPIServiceWatchNamespaceStateYARPCServer sends WatchNamespaceStateResponses.
type ShardDistributorAPIServiceWatchNamespaceStateYARPCServer interface {
	Context() context.Context
	Send(*WatchNamespaceStateResponse, ...yarpc.StreamOption) error
}

type buildShardDistributorAPIYARPCProceduresParams struct {
	Server      ShardDistributorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildShardDistributorAPIYARPCProcedures(params buildShardDistributorAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_ShardDistributorAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "GetShardOwner",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.GetShardOwner,
							NewRequest:  newShardDistributorAPIServiceGetShardOwnerYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{

				{
					MethodName: "WatchNamespaceState",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.WatchNamespaceState,
						},
					),
				},
			},
		},
	)
}

// BuildShardDistributorAPIYARPCProcedures prepares an implementation of the ShardDistributorAPI service for YARPC registration.
func BuildShardDistributorAPIYARPCProcedures(server ShardDistributorAPIYARPCServer) []transport.Procedure {
	return buildShardDistributorAPIYARPCProcedures(buildShardDistributorAPIYARPCProceduresParams{Server: server})
}

// FxShardDistributorAPIYARPCClientParams defines the input
// for NewFxShardDistributorAPIYARPCClient. It provides the
// paramaters to get a ShardDistributorAPIYARPCClient in an
// Fx application.
type FxShardDistributorAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxShardDistributorAPIYARPCClientResult defines the output
// of NewFxShardDistributorAPIYARPCClient. It provides a
// ShardDistributorAPIYARPCClient to an Fx application.
type FxShardDistributorAPIYARPCClientResult struct {
	fx.Out

	Client ShardDistributorAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxShardDistributorAPIYARPCClient provides a ShardDistributorAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxShardDistributorAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxShardDistributorAPIYARPCClientParams) FxShardDistributorAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxShardDistributorAPIYARPCClientResult{
			Client: newShardDistributorAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxShardDistributorAPIYARPCProceduresParams defines the input
// for NewFxShardDistributorAPIYARPCProcedures. It provides the
// paramaters to get ShardDistributorAPIYARPCServer procedures in an
// Fx application.
type FxShardDistributorAPIYARPCProceduresParams struct {
	fx.In

	Server      ShardDistributorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxShardDistributorAPIYARPCProceduresResult defines the output
// of NewFxShardDistributorAPIYARPCProcedures. It provides
// ShardDistributorAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxShardDistributorAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxShardDistributorAPIYARPCProcedures provides ShardDistributorAPIYARPCServer procedures to an Fx application.
// It expects a ShardDistributorAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorAPIYARPCProcedures(),
//	  ...
//	)
func NewFxShardDistributorAPIYARPCProcedures() interface{} {
	return func(params FxShardDistributorAPIYARPCProceduresParams) FxShardDistributorAPIYARPCProceduresResult {
		return FxShardDistributorAPIYARPCProceduresResult{
			Procedures: buildShardDistributorAPIYARPCProcedures(buildShardDistributorAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: ShardDistributorAPIReflectionMeta,
		}
	}
}

// ShardDistributorAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var ShardDistributorAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
	FileDescriptors: yarpcFileDescriptorClosure0055bfd59dff1f95,
}

type _ShardDistributorAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_ShardDistributorAPIYARPCCaller) GetShardOwner(ctx context.Context, request *GetShardOwnerRequest, options ...yarpc.CallOption) (*GetShardOwnerResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetShardOwner", request, newShardDistributorAPIServiceGetShardOwnerYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetShardOwnerResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetShardOwnerYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) WatchNamespaceState(ctx context.Context, request *WatchNamespaceStateRequest, options ...yarpc.CallOption) (ShardDistributorAPIServiceWatchNamespaceStateYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "WatchNamespaceState", options...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(request); err != nil {
		return nil, err
	}
	return &_ShardDistributorAPIServiceWatchNamespaceStateYARPCClient{stream: stream}, nil
}

type _ShardDistributorAPIYARPCHandler struct {
	server ShardDistributorAPIYARPCServer
}

func (h *_ShardDistributorAPIYARPCHandler) GetShardOwner(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetShardOwnerRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetShardOwnerRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetShardOwnerYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetShardOwner(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) WatchNamespaceState(serverStream *protobuf.ServerStream) error {
	requestMessage, err := serverStream.Receive(newShardDistributorAPIServiceWatchNamespaceStateYARPCRequest)
	if requestMessage == nil {
		return err
	}

	request, ok := requestMessage.(*WatchNamespaceStateRequest)
	if !ok {
		return protobuf.CastError(emptyShardDistributorAPIServiceWatchNamespaceStateYARPCRequest, requestMessage)
	}
	return h.server.WatchNamespaceState(request, &_ShardDistributorAPIServiceWatchNamespaceStateYARPCServer{serverStream: serverStream})
}

type _ShardDistributorAPIServiceWatchNamespaceStateYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_ShardDistributorAPIServiceWatchNamespaceStateYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_ShardDistributorAPIServiceWatchNamespaceStateYARPCClient) Recv(options ...yarpc.StreamOption) (*WatchNamespaceStateResponse, error) {
	responseMessage, err := c.stream.Receive(newShardDistributorAPIServiceWatchNamespaceStateYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*WatchNamespaceStateResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceWatchNamespaceStateYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIServiceWatchNamespaceStateYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _ShardDistributorAPIServiceWatchNamespaceStateYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_ShardDistributorAPIServiceWatchNamespaceStateYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_ShardDistributorAPIServiceWatchNamespaceStateYARPCServer) Send(response *WatchNamespaceStateResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

func newShardDistributorAPIServiceGetShardOwnerYARPCRequest() proto.Message {
	return &GetShardOwnerRequest{}
}

func newShardDistributorAPIServiceGetShardOwnerYARPCResponse() proto.Message {
	return &GetShardOwnerResponse{}
}

func newShardDistributorAPIServiceWatchNamespaceStateYARPCRequest() proto.Message {
	return &WatchNamespaceStateRequest{}
}

func newShardDistributorAPIServiceWatchNamespaceStateYARPCResponse() proto.Message {
	return &WatchNamespaceStateResponse{}
}

var (
	emptyShardDistributorAPIServiceGetShardOwnerYARPCRequest        = &GetShardOwnerRequest{}
	emptyShardDistributorAPIServiceGetShardOwnerYARPCResponse       = &GetShardOwnerResponse{}
	emptyShardDistributorAPIServiceWatchNamespaceStateYARPCRequest  = &WatchNamespaceStateRequest{}
	emptyShardDistributorAPIServiceWatchNamespaceStateYARPCResponse = &WatchNamespaceStateResponse{}
)

var yarpcFileDescriptorClosure0055bfd59dff1f95 = [][]byte{
	// uber/cadence/sharddistributor/v1/service.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
		0x14, 0x96, 0x53, 0x81, 0x96, 0x33, 0x26, 0x21, 0x6f, 0xa0, 0xaa, 0x03, 0x51, 0xe5, 0x6a, 0x57,
		0x0e, 0x1d, 0xd2, 0x40, 0x1b, 0x5c, 0x80, 0x28, 0xa8, 0x1a, 0x6c, 0x90, 0x5d, 0x80, 0xb8, 0x99,
		0x9c, 0xe4, 0xb0, 0x46, 0xa3, 0x76, 0xb1, 0x9d, 0x40, 0xef, 0x78, 0x08, 0xde, 0x83, 0xa7, 0xe2,
		0x8a, 0x97, 0x40, 0x71, 0x93, 0x66, 0x89, 0xb2, 0x8d, 0x96, 0xbb, 0xf8, 0xfc, 0x7c, 0xfe, 0x7c,
		0xbe, 0x2f, 0x07, 0x58, 0x1a, 0xa2, 0xf2, 0x23, 0x1e, 0xa3, 0x88, 0xd0, 0xd7, 0x63, 0xae, 0xe2,
		0x38, 0xd1, 0x46, 0x25, 0x61, 0x6a, 0xa4, 0xf2, 0xb3, 0x81, 0xaf, 0x51, 0x65, 0x49, 0x84, 0x6c,
		0xaa, 0xa4, 0x91, 0xb4, 0x9f, 0xd7, 0xb3, 0xa2, 0x9e, 0x35, 0xeb, 0x59, 0x36, 0xf0, 0xde, 0xc3,
		0xd6, 0x6b, 0x34, 0x27, 0x79, 0xe6, 0xf8, 0x9b, 0x40, 0x15, 0xe0, 0xd7, 0x14, 0xb5, 0xa1, 0xdb,
		0xe0, 0xda, 0xf2, 0xd3, 0x73, 0x9c, 0x75, 0x49, 0x9f, 0xec, 0xb8, 0xc1, 0x9a, 0x0d, 0x1c, 0xe2,
		0x8c, 0xde, 0x03, 0x57, 0xf0, 0x09, 0xea, 0x29, 0x8f, 0xb0, 0xeb, 0xd8, 0x64, 0x15, 0xf0, 0xfe,
		0x10, 0xb8, 0xd3, 0xc0, 0xd4, 0x53, 0x29, 0x34, 0xd2, 0x2d, 0xb8, 0x21, 0xf3, 0x40, 0x01, 0x38,
		0x3f, 0x5c, 0x8d, 0x46, 0x39, 0xac, 0x4d, 0xd0, 0xf0, 0x98, 0x1b, 0xde, 0xed, 0xf4, 0x3b, 0x3b,
		0xeb, 0xbb, 0x43, 0x76, 0xdd, 0xab, 0x58, 0xeb, 0xf5, 0xec, 0x6d, 0x81, 0x33, 0x14, 0x46, 0xcd,
		0x82, 0x05, 0x6c, 0xef, 0x00, 0x36, 0x6a, 0x29, 0x7a, 0x1b, 0x3a, 0xd5, 0xb3, 0xf3, 0xcf, 0x9c,
		0x79, 0xc6, 0xbf, 0xa4, 0x25, 0xbf, 0xf9, 0x61, 0xdf, 0x79, 0x42, 0xbc, 0x3d, 0xb8, 0x7b, 0x54,
		0x92, 0x3d, 0x92, 0xe6, 0x95, 0x4c, 0x45, 0x3c, 0x54, 0x4a, 0x36, 0xde, 0x45, 0x9a, 0x53, 0x3a,
		0x06, 0x6a, 0x29, 0x2e, 0xd1, 0x53, 0x17, 0xc5, 0xa9, 0x8b, 0xe2, 0xed, 0x43, 0xef, 0x03, 0x37,
		0xd1, 0x78, 0xc1, 0xe6, 0xc4, 0x70, 0x83, 0xa5, 0x9e, 0x57, 0x93, 0x39, 0x87, 0xed, 0xd6, 0xde,
		0x42, 0xb7, 0x37, 0xe0, 0xe2, 0x77, 0x8c, 0xf2, 0xe9, 0xea, 0x2e, 0xb1, 0x22, 0xb0, 0xeb, 0x45,
		0x18, 0x16, 0x2d, 0x23, 0xf1, 0x59, 0x06, 0x15, 0x80, 0xf7, 0x9b, 0xc0, 0xad, 0x8b, 0x39, 0xfa,
		0x00, 0xd6, 0xcb, 0xec, 0x69, 0x12, 0x17, 0xec, 0xa0, 0x0c, 0x8d, 0x62, 0xfa, 0xf1, 0x82, 0x07,
		0x1c, 0x7b, 0xfd, 0xd3, 0xe5, 0xae, 0xbf, 0x4c, 0x7a, 0x7a, 0x1f, 0x60, 0x31, 0x51, 0x6d, 0xfd,
		0xe5, 0x06, 0x6e, 0x39, 0x52, 0xfd, 0x5f, 0xce, 0xd8, 0xfd, 0xe5, 0xc0, 0xa6, 0x95, 0xf8, 0x65,
		0x45, 0xec, 0xf9, 0xbb, 0x11, 0xfd, 0x41, 0x60, 0xa3, 0x66, 0x50, 0xba, 0xb7, 0xb4, 0xa3, 0xad,
		0xa8, 0xbd, 0xc7, 0x2b, 0xfe, 0x09, 0xf4, 0x27, 0x81, 0xcd, 0x16, 0xc1, 0xe9, 0x3f, 0x8c, 0xf5,
		0x72, 0x8f, 0xf5, 0x9e, 0xad, 0xd8, 0x3d, 0x27, 0xf5, 0x90, 0xbc, 0x38, 0xfc, 0x34, 0x3a, 0x4b,
		0xcc, 0x38, 0x0d, 0x59, 0x24, 0x27, 0x7e, 0x6d, 0xd7, 0xb1, 0x33, 0x14, 0xbe, 0x5d, 0x6a, 0x6d,
		0x6b, 0xef, 0xa0, 0x19, 0xcb, 0x06, 0xe1, 0x4d, 0x5b, 0xfd, 0xe8, 0x6f, 0x00, 0x00, 0x00, 0xff,
		0xff, 0x8f, 0xa9, 0xd5, 0x92, 0x34, 0x05, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) ShardDistributorAPIYARPCClient {
			return NewShardDistributorAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
