global:
  scrape_interval: 5s
  external_labels:
    monitor: 'cadence-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: # addresses to scrape
          - 'host.docker.internal:9090'
          - 'host.docker.internal:8000'
          - 'host.docker.internal:8001'
          - 'host.docker.internal:8002'
          - 'host.docker.internal:8003'
          - 'host.docker.internal:8004'
          - 'host.docker.internal:8005'
